version: '2'
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    volumes:
      - ./front-envoy.json:/etc/front-envoy.json
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  service-a:
    build:
      context: ./service-a
    volumes:
      - './service-a-envoy.json:/etc/service-envoy.json:ro'
    networks:
      envoymesh:
        aliases:
          - service-a
    environment:
      - SERVICE_NAME=A
    expose:
      - "80"

  service-b:
    build:
      context: ./service-b
    volumes:
      - './service-b-envoy.json:/etc/service-envoy.json:ro'
    networks:
      envoymesh:
        aliases:
          - service-b
    environment:
      - SERVICE_NAME=B
    expose:
      - "80"

networks:
  envoymesh: {}
